version: '3.8'

services:
  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password@postgres:5432/todoapp
    volumes:
      - ./packages/backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:3000
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"