version: '3.8'

services:
  postgres:
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-todoapp}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:password@postgres:5432/todoapp}
    restart: always
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    restart: always
    ports:
      - "3001:3001"

  # Load balancer for production
  nginx:
    image: nginx:1.25-alpine
    container_name: todo-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - todo-network