name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        task: [typecheck, biome, build, test, openapi-check]
      fail-fast: false
    steps:
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup mise
        uses: jdx/mise-action@bb86feacf6eb957c0a295df514530390b68009a4 # v2.2.3
        with:
          install: true
          cache: true

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Install Playwright browsers
        if: matrix.task == 'test'
        run: bun x playwright install --with-deps chromium

      - name: Run TypeScript type check
        if: matrix.task == 'typecheck'
        run: bun run typecheck

      - name: Run Biome check
        if: matrix.task == 'biome'
        run: bun run check

      - name: Build all packages
        if: matrix.task == 'build'
        run: bun run build

      - name: Run tests
        if: matrix.task == 'test'
        run: bun run test
        env:
          CI: true
          PLAYWRIGHT_BROWSERS_PATH: 0

      - name: Generate OpenAPI schema
        if: matrix.task == 'openapi-check'
        run: bun --cwd packages/backend run generate

      - name: Check for OpenAPI schema changes
        if: matrix.task == 'openapi-check'
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "❌ OpenAPI schema files have been changed after generation:"
            git status --porcelain
            echo ""
            echo "The following files have been modified:"
            git diff --name-only
            echo ""
            echo "Please run 'bun run generate' locally and commit the changes."
            exit 1
          else
            echo "✅ No OpenAPI schema changes detected"
          fi
